/** @file ConfigStdStructDefs.h
  Standard structure definitions shared by core code and KnobService.py
  autogenerated code.

  Copyright (c) Microsoft Corporation.
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef CONFIG_STD_STRUCT_DEFS_LIB_H_
#define CONFIG_STD_STRUCT_DEFS_LIB_H_

/*
 * Standard structure definitons that KnobService.py autogenerated
 * headers and core code use.
 */
typedef BOOLEAN (KNOB_VALIDATION_FN)(
  CONST VOID *
  );

typedef struct {
  UINTN                 Knob;
  CONST VOID            *DefaultValueAddress;
  VOID                  *CacheValueAddress;
  UINT32                ValueSize;
  CONST CHAR8           *Name;
  UINT32                NameSize;
  EFI_GUID              VendorNamespace;
  UINT32                Attributes;
  KNOB_VALIDATION_FN    *Validator;
} KNOB_DATA;

#endif // CONFIG_STD_STRUCT_DEFS_LIB_H_
