/** @file c.h

  Autogenerated configuration headers from mu_feature_config

  Copyright (c) Microsoft Corporation.
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef C_H
#define C_H
#include <Uefi.h>
// Generated Header
//  Script: KnobService.py
//  Schema: ..\..\..\mu_tiano_platforms\Platforms\QemuQ35Pkg\CfgData\QemuQ35PkgCfgData.xml

#pragma pack(push, 1)
// Schema-defined enums
// Schema-defined structures
#pragma pack(pop)

// Schema-defined knobs
// DummyKnob1 knob


EFI_STATUS ConfigGetDummyKnob1 (UINT32 *Knob);
// DummyKnob2 knob


EFI_STATUS ConfigGetDummyKnob2 (UINT32 *Knob);
// PowerOnPort0 knob


EFI_STATUS ConfigGetPowerOnPort0 (BOOLEAN *Knob);
// DummyKnob3 knob


EFI_STATUS ConfigGetDummyKnob3 (UINT32 *Knob);

#define KNOB_DummyKnob1 0
#define KNOB_DummyKnob2 1
#define KNOB_PowerOnPort0 2
#define KNOB_DummyKnob3 3
#define KNOB_MAX 4
typedef struct {
  KNOB Knob;
  VOID * Value;
} KNOB_OVERRIDE;

typedef struct {
  KNOB_OVERRIDE* Overrides;
  UINTN OverrideCount;
} PROFILE;

#endif // C_H
