## @file
# Azure Pipeline build file for a build using ubuntu and GCC5
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020, Hewlett Packard Enterprise Development LP. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

trigger:
- main

pr:
- main

schedules:
- cron: "30 9 * * 0"  # Sun/Wed at 2:30AM Pacific
  displayName: Sun Build
  branches:
    include:
    - main
  always: true          # Always build, even if no changes

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: IA32,X64,ARM,AARCH64
    do_ci_build: true
    do_ci_setup: false
    extra_steps:
    - script: sudo apt-get install mingw-w64
      displayName: Install Windows Resource Compiler for Linux
    packages: SetupDataPkg
    target_list: DEBUG,RELEASE,NO-TARGET,NOOPT
    tool_chain_tag: GCC5
    vm_image: ubuntu-latest

- template: Jobs/Python/RunDevTests.yml@mu_devops
  parameters:
    code_cov_enabled: true
    custom_job_name: ubuntu
    root_package_folder: SetupDataPkg/Tools
    vm_image: ubuntu-latest
