## @file
# Azure Pipeline build file for a build using ubuntu and GCC5
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020, Hewlett Packard Enterprise Development LP. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
# MU_CHANGE BEGIN
trigger:
- main

schedules:
- cron: "30 9 * * 0"  # Sun/Wed at 2:30AM Pacific
  displayName: Sun Build
  branches:
    include:
    - main
  always: true          # Always build, even if no changes

pr:
- main
# MU_CHANGE END

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'GCC5'
    vm_image: 'ubuntu-latest'
    arch_list: "IA32,X64,ARM,AARCH64"
    # MU_CHANGE
    extra_steps:
    - script: sudo apt-get install mingw-w64
      displayName: Install Windows Resource Compiler for Linux

