## @file
# Azure Pipeline build file for a build using Windows and Visual Studio
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

variables:
- group: architectures-x86-64
- group: tool-chain-windows-visual-studio-latest

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: $(arch_list)
    do_ci_build: true
    do_ci_setup: false
    packages: SetupDataPkg
    target_list: DEBUG,RELEASE,NO-TARGET,NOOPT
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)

- template: Jobs/Python/RunDevTests.yml@mu_devops
  parameters:
    code_cov_enabled: true
    custom_job_name: windows
    root_package_folder: SetupDataPkg/Tools
    vm_image: $(vm_image)
